# Generated by Django 5.1.3 on 2024-11-19 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mahsulot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomi", models.CharField(max_length=100)),
                ("tarifi", models.TextField()),
                ("narxi", models.DecimalField(decimal_places=2, max_digits=10)),
                ("miqdori", models.IntegerField()),
            ],
            options={
                "verbose_name": "Mahsulot",
                "verbose_name_plural": "Mahsulotlar",
            },
        ),
        migrations.CreateModel(
            name="Sotuv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("miqdori", models.IntegerField()),
                ("jami_narxi", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sana", models.DateTimeField(auto_now_add=True)),
                (
                    "mahsulot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.mahsulot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sotuv",
                "verbose_name_plural": "Sotuvlar",
            },
        ),
    ]
